name: Run salt tests
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    uses: plus3it/actions-workflows/.github/workflows/test-salt-windows.yml@0054f1b21931641f08f755c8115375b8099f7f6b
    strategy:
      matrix:
        os_version:
          - windows-2019
          - windows-2022
        salt_state:
          - windows-update-agent
        salt_pillar_root:
          - ./tests/pillar/test-main
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}
